title = "Odilia Screen Reader"
baseURL = "https://odilia.app"
languageCode = "en-us"

[taxonomies]
	author = "authors"
        tag = "tags"

[markup]
  [markup.highlight]
    guessSyntax = true
    lineNos = true
    noClasses = false

[menu]
  [[menu.main]]
  title = "Code"
  url = "https://github.com/odilia-app"
  weight =  -100
